### ISSUE TITLE
Config file location

### ISSUE THREAD

**Issue by TheMiz1os** [Coosanta17/crafty_discord_bot#3]
I am new to linux and programming in general and I get confused pretty easily. I can't understand where is the actual config file I should edit to make the bot work. I don't know the etiquette for posting issues in this platform, so I hope I did't break any rules with this short post and probably stupid question. 

Thank you for your help

**Comment by Coosanta17** [comment]
Hi, apologies for the confusion, upon revisiting the README I have realised how unclear it is.

You can download the source code from the [releases page](https://github.com/Coosanta17/crafty_discord_bot/releases), unzip it into the folder you wish to run the bot from. If you're using linux, you can use the unzip command (you can install with `sudo apt-get install unzip` if it isn't already installed and run `unzip file.zip -d /path/to/destination_folder` in the folder the file is downloaded in (you can use the `cd` command to get the terminal there), or use the gui if you have a desktop environment. 

Once you have the extracted source code in the right place, run terminal in the folder, don't run it in the src folder but rather one folder up. So if the src folder is at `/path/to/crafty_bot/src/` you will run terminal in the path of `/path/to/crafty_bot/`. To create a config file, run the bot for the first time (first run `npm install` then `node .` -- make sure you have [node.js](https://nodejs.org/en) installed), it should log something about creating config files in terminal and the path that it is located at, then shut down. You can follow the path provided by the bot, or look one folder up from src folder (`/path/to/crafty_bot/`).

When [everything has been configured](https://github.com/Coosanta17/crafty_discord_bot?tab=readme-ov-file#configuration-file), you can run the bot again using the command `node .`.

**Comment by TheMiz1os** [comment]
Thank you for the reply! 
Unfortunately it still gives me the same error as before; I also tried to manually create the config file in various directories but it doesn't seem to see it nor create it. I also did a bit of reverse engineering with help from gpt4, but even when creating a _config.json_ file in the directory specified in _config.js_'  configPath variable, it always gives me this error:
```
root@Crafty-Discord-Bot:/home/crafty-bot/crafty_discord_bot-1.0# node .
file:///home/crafty-bot/crafty_discord_bot-1.0/src/bot.js:4
await checkConfigFile();
^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```
The `npm install` command seems successful so I don't think that is the problem, but I'm still guessing.

**Comment by TheMiz1os** [comment]
Thank you for the reply!
Unfortunately it still gives me the same error as before; I also tried to manually create the config file in various directories but it doesn't seem to see it nor create it. I also did a bit of reverse engineering with help from gpt4, but even when creating a _config.json_ file in the directory specified in _config.js_' configPath variable, it always gives me this error:
```
root@Crafty-Discord-Bot:/home/crafty-bot/crafty_discord_bot-1.0# node .
file:///home/crafty-bot/crafty_discord_bot-1.0/src/bot.js:4
await checkConfigFile();
^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```
The `npm install` command seems successful so I don't think that is the problem, but I'm still guessing.

Edit: I closed the thing as a mistake, sorry for the confusion.

**Comment by Coosanta17** [comment]
The error mentioned a syntax error on a supported node feature. A possibility could be an outdated node version, again README doesn't specify the version (but it should!). If you haven't already, try updating (or downgrading) node. I currently use v20.13.1 and the bot has been tested in that version, I'm not sure whether it works in later versions.

**Comment by TheMiz1os** [comment]
That solved it, thank you so much! Now I can finally live in peace and not get called at all moments!
I'll be looking forward to future updates ;) It would really be useful to edit the time it takes for an empty server to close.
